sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '0351'
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tNirDEEda4X2D4jR72j
    access-key-secret: pGzR3dKA5WBsxNWog1XtwIoocM9U3N
    bucket-name: s-k-y-t-a-k-e-o-u-t
  redis:
    host: localhost
    port: 6379
    auth: '0351'
    database: 0
